import {
  RiCalendarLine,
  RiCloseLine,
  RiExpandUpDownFill,
  RiFilePdf2Fill,
  RiFunctionLine,
  RiGalleryLine,
  RiGameLine,
  RiGithubLine,
  RiListSettingsLine,
  RiLoader5Line,
  RiMoonLine,
  RiSearch2Line,
  RiSkipLeftLine,
  RiSkipRightLine,
  RiStarFill,
  RiStarHalfFill,
  RiStarLine,
  RiSunLine,
  RiYoutubeLine,
} from 'react-icons/ri';

export const iconMap: Record<Props.Icons['type'], React.ReactElement> = {
  download: <RiFilePdf2Fill />,
  selector: <RiExpandUpDownFill />,
  spinner: <RiLoader5Line />,
  next: <RiSkipRightLine />,
  previous: <RiSkipLeftLine />,
  youtube: <RiYoutubeLine />,
  star: <RiStarFill />,
  starLine: <RiStarLine />,
  starHalf: <RiStarHalfFill />,
  category: <RiFunctionLine />,
  platform: <RiGameLine />,
  screenshot: <RiGalleryLine />,
  date: <RiCalendarLine />,
  list: <RiListSettingsLine />,
  search: <RiSearch2Line />,
  close: <RiCloseLine />,
  sun: <RiSunLine />,
  moon: <RiMoonLine />,
  github: <RiGithubLine />,
};
