import {
  RiCalendar2Line,
  RiExpandUpDownFill,
  RiFilePdf2Fill,
  RiFunctionLine,
  RiGalleryLine,
  RiGameLine,
  RiListSettingsLine,
  RiLoader5Line,
  RiSearch2Line,
  RiSkipLeftLine,
  RiSkipRightLine,
  RiStarFill,
  RiStarLine,
  RiYoutubeLine,
} from 'react-icons/ri';

export const iconMap: Record<Props.Icons['type'], React.ReactElement> = {
  download: <RiFilePdf2Fill />,
  selector: <RiExpandUpDownFill />,
  spinner: <RiLoader5Line />,
  next: <RiSkipRightLine />,
  previous: <RiSkipLeftLine />,
  youtube: <RiYoutubeLine />,
  star: <RiStarFill />,
  starLine: <RiStarLine />,
  category: <RiFunctionLine />,
  platform: <RiGameLine />,
  screenshot: <RiGalleryLine />,
  date: <RiCalendar2Line />,
  list: <RiListSettingsLine />,
  search: <RiSearch2Line />,
};
