export const gamelist = [
  {
    i: 1,
    n: 'The X-Files Game',
    l: 'https://www.mobygames.com/game/1/the-x-files-game/',
    d: '<p>As an extension of one of the most long-running television series of all time, <em>The X-Files</em>, play through the eyes of Special Agent Craig Willmore, a new FBI field investigator brought in to locate missing agents Fox Mulder and Dana Scully whose last location was the E',
    c: 'https://cdn.mobygames.com/covers/4062982-the-x-files-game-windows-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/11075554-the-x-files-game-windows-dockside-warehouse-under-surveillance.jpg',
      'https://cdn.mobygames.com/screenshots/11073355-the-x-files-game-windows-arriving-at-comity-inn.jpg',
      'https://cdn.mobygames.com/screenshots/11076738-the-x-files-game-windows-a-cigarette.jpg',
      'https://cdn.mobygames.com/screenshots/3874741-the-x-files-game-windows-agent-willmores-office-and-the-inventor.jpg',
      'https://cdn.mobygames.com/screenshots/10471109-the-x-files-game-playstation-catching-on-some-clues-wrong-answer.jpg',
    ],
    g: [0, 1, 2, 3, 4, 5],
    p: [0, 1, 2],
  },
  {
    i: 92,
    n: 'Altered Destiny',
    l: 'https://www.mobygames.com/game/92/altered-destiny/',
    d: '<p>One fine day P. J. Barrett, an ordinary human being from the planet Earth, goes to a repair shop to get his TV set fixed. When he comes back for it, he accidentally picks up the wrong one. No big deal? Quite on the contrary. When the unsuspecting Mr. Barrett returns home and t',
    c: 'https://cdn.mobygames.com/covers/3899950-altered-destiny-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/1694785-altered-destiny-dos-the-floating-village.png',
      'https://cdn.mobygames.com/screenshots/15806627-altered-destiny-amiga-help-screen.png',
      'https://cdn.mobygames.com/screenshots/1695597-altered-destiny-dos-ask-the-sage-a-question.png',
      'https://cdn.mobygames.com/screenshots/16048600-altered-destiny-amiga-copy-protection.png',
      'https://cdn.mobygames.com/screenshots/15806993-altered-destiny-amiga-intro-tv-repair-shop.png',
    ],
    g: [0, 39, 44, 45, 3],
    p: [3, 0, 4],
  },
  {
    i: 98,
    n: 'Rise of the Dragon',
    l: 'https://www.mobygames.com/game/98/rise-of-the-dragon/',
    d: "<p>The year is 2053, and Los Angeles has turned into a grim place ruled by crime and corruption. William 'Blade' Hunter is a private detective who once was a police officer. He is asked to investigate a horrible murder of the mayor's daughter, whose body was mutilated. As Hunter ",
    c: 'https://cdn.mobygames.com/covers/4014463-rise-of-the-dragon-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/16460458-rise-of-the-dragon-amiga-discussion-with-the-mayor.png',
      'https://cdn.mobygames.com/screenshots/2348780-rise-of-the-dragon-dos-id-do-as-he-says-if-i-were-you.png',
      'https://cdn.mobygames.com/screenshots/15756165-rise-of-the-dragon-sega-cd-one-of-the-arcade-segments-near-the-e.png',
      'https://cdn.mobygames.com/screenshots/11584691-rise-of-the-dragon-macintosh-the-em-way.png',
      'https://cdn.mobygames.com/screenshots/16460437-rise-of-the-dragon-amiga-downtown.png',
    ],
    g: [0, 1, 44, 80, 4],
    p: [3, 0, 4, 9, 2],
  },
  {
    i: 116,
    n: 'Gabriel Knight: Sins of the Fathers',
    l: 'https://www.mobygames.com/game/116/gabriel-knight-sins-of-the-fathers/',
    d: '<p>Gabriel Knight is a wise-cracking bookstore owner and would-be author. He is the last in a long line of Shadow Hunters, those fated to fight supernatural forces of evil. Tormented by terrifying nightmares, he must spend every waking moment scouring the side streets and back al',
    c: 'https://cdn.mobygames.com/covers/10943030-gabriel-knight-sins-of-the-fathers-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/1264759-gabriel-knight-sins-of-the-fathers-dos-bloody-ritual.png',
      'https://cdn.mobygames.com/screenshots/12166030-gabriel-knight-sins-of-the-fathers-dos-this-video-animation-show.png',
      'https://cdn.mobygames.com/screenshots/8787484-gabriel-knight-sins-of-the-fathers-dos-like-in-most-sierra-games.png',
      'https://cdn.mobygames.com/screenshots/8787481-gabriel-knight-sins-of-the-fathers-dos-bookstore-gabriels-home-b.png',
      'https://cdn.mobygames.com/screenshots/8786915-gabriel-knight-sins-of-the-fathers-dos-the-map-of-french-distric.png',
    ],
    g: [0, 36, 49, 44, 45, 20, 4, 79],
    p: [3, 0, 16, 2],
  },
  {
    i: 118,
    n: 'The Beast Within: A Gabriel Knight Mystery',
    l: 'https://www.mobygames.com/game/118/the-beast-within-a-gabriel-knight-mystery/',
    d: '<p><em>The Beast Within: A Gabriel Knight Mystery</em> is a direct sequel to <a href="https://www.mobygames.com/game/116/gabriel-knight-sins-of-the-fathers/">Gabriel Knight: Sins of the Fathers</a>, the first in the supernatural mystery adventure series telling the story of a boo',
    c: 'https://cdn.mobygames.com/covers/416469-the-beast-within-a-gabriel-knight-mystery-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/109403-the-beast-within-a-gabriel-knight-mystery-dos-yup-these-things-h.png',
      'https://cdn.mobygames.com/screenshots/95513-the-beast-within-a-gabriel-knight-mystery-windows-gerda-a-firey-.png',
      'https://cdn.mobygames.com/screenshots/107424-the-beast-within-a-gabriel-knight-mystery-dos-while-in-wolfs-sha.png',
      'https://cdn.mobygames.com/screenshots/8690773-the-beast-within-a-gabriel-knight-mystery-dos-certain-key-events.png',
      'https://cdn.mobygames.com/screenshots/12314189-the-beast-within-a-gabriel-knight-mystery-windows-it-was-a-close.jpg',
    ],
    g: [0, 39, 45, 20, 4, 79],
    p: [3, 0, 16, 2],
  },
  {
    i: 132,
    n: 'Call of Cthulhu: Shadow of the Comet',
    l: 'https://www.mobygames.com/game/132/call-of-cthulhu-shadow-of-the-comet/',
    d: "<p>In 1834, in the small New England fishing village of Illsmouth, the distinguished British scientist Lord Boleskine lost his mind. After studying ancient manuscripts of evil repute, he had travelled to this place to observe the passing of Halley's comet. What he observed that n",
    c: 'https://cdn.mobygames.com/covers/4022611-call-of-cthulhu-shadow-of-the-comet-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/15647947-call-of-cthulhu-shadow-of-the-comet-pc-98-its-easy-to-get-lost.png',
      'https://cdn.mobygames.com/screenshots/16099292-call-of-cthulhu-shadow-of-the-comet-pc-98-the-graphics-in-this-g.png',
      'https://cdn.mobygames.com/screenshots/16098386-call-of-cthulhu-shadow-of-the-comet-pc-98-do-you-feel-patriotic.png',
      'https://cdn.mobygames.com/screenshots/16098383-call-of-cthulhu-shadow-of-the-comet-pc-98-arriving-at-the-sleepy.png',
      'https://cdn.mobygames.com/screenshots/16098314-call-of-cthulhu-shadow-of-the-comet-pc-98-this-cu-scene-is-displ.png',
    ],
    g: [0, 36, 44, 45, 34, 79, 5],
    p: [35, 3, 0, 26],
  },
  {
    i: 135,
    n: "Roberta Williams' King's Quest VII: The Princeless Bride",
    l: 'https://www.mobygames.com/game/135/roberta-williams-kings-quest-vii-the-princeless-bride/',
    d: '<p>Queen Valanice of Daventry has always thought that getting married would be the best course of action for her daughter Rosella. However, the young princess seems to be more interested in adventure, recklessly following a mysterious magical creature into a whirlpool that eventu',
    c: 'https://cdn.mobygames.com/covers/9205765-roberta-williams-kings-quest-vii-the-princeless-bride-dos-front-.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/12247543-roberta-williams-kings-quest-vii-the-princeless-bride-dos-the-gr.png',
      'https://cdn.mobygames.com/screenshots/12246743-roberta-williams-kings-quest-vii-the-princeless-bride-dos-the-in.png',
      'https://cdn.mobygames.com/screenshots/16746370-roberta-williams-kings-quest-vii-the-princeless-bride-windows-a-.png',
      'https://cdn.mobygames.com/screenshots/1359898-roberta-williams-kings-quest-vii-the-princeless-bride-dos-no-kin.png',
      'https://cdn.mobygames.com/screenshots/16746361-roberta-williams-kings-quest-vii-the-princeless-bride-windows-tr.png',
    ],
    g: [0, 39, 44, 45, 20, 60],
    p: [3, 0, 16, 2],
  },
  {
    i: 136,
    n: "King's Quest: Mask of Eternity",
    l: 'https://www.mobygames.com/game/136/kings-quest-mask-of-eternity/',
    d: '<p>The Realm of Sun is a magical world situated above the Kingdom of Daventry. Powerful beings known as Archons dwell there, guarding the Mask of Eternity, which preserves balance in the world. But on an ominous day, Lucreto, the leader of the Archons, turns evil and shatters the',
    c: 'https://cdn.mobygames.com/covers/3979754-kings-quest-mask-of-eternity-windows-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/16813561-kings-quest-mask-of-eternity-windows-thought-perhaps-its-not-yet.png',
      'https://cdn.mobygames.com/screenshots/9113804-kings-quest-mask-of-eternity-windows-pick-up-and-eat-the-mushroo.jpg',
      'https://cdn.mobygames.com/screenshots/10276386-kings-quest-mask-of-eternity-windows-a-daventry-fountain.jpg',
      'https://cdn.mobygames.com/screenshots/583602-kings-quest-mask-of-eternity-windows-title-screen.jpg',
      'https://cdn.mobygames.com/screenshots/10270528-kings-quest-mask-of-eternity-windows-receiving-a-map-from-the-wi.jpg',
    ],
    g: [6, 0, 78, 1, 33, 45, 60],
    p: [0],
  },
  {
    i: 145,
    n: 'Space Quest 6: Roger Wilco in the Spinal Frontier',
    l: 'https://www.mobygames.com/game/145/space-quest-6-roger-wilco-in-the-spinal-frontier/',
    d: '<p>Roger Wilco, the brave interstellar janitor who has already saved the universe from many great dangers, is now in a very embarrassing position. His commanders show no respect for his courageous actions in the <a href="https://www.mobygames.com/game/144/space-quest-v-the-next-m',
    c: 'https://cdn.mobygames.com/covers/4028930-space-quest-6-roger-wilco-in-the-spinal-frontier-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/9895156-space-quest-6-roger-wilco-in-the-spinal-frontier-dos-a-message-f.png',
      'https://cdn.mobygames.com/screenshots/1924395-space-quest-6-roger-wilco-in-the-spinal-frontier-windows-3x-hote.jpg',
      'https://cdn.mobygames.com/screenshots/9894403-space-quest-6-roger-wilco-in-the-spinal-frontier-dos-stellas-fun.png',
      'https://cdn.mobygames.com/screenshots/10408398-space-quest-6-roger-wilco-in-the-spinal-frontier-windows-3x-in-t.jpg',
      'https://cdn.mobygames.com/screenshots/12024110-space-quest-6-roger-wilco-in-the-spinal-frontier-windows-3x-inve.png',
    ],
    g: [0, 36, 44, 45, 20, 3, 55],
    p: [3, 0, 16, 2],
  },
  {
    i: 157,
    n: 'Cyberswine',
    l: 'https://www.mobygames.com/game/157/cyberswine/',
    d: '<p>The protagonist of <em>Cyberswine</em> is, as the title implies, a cybernetic pig on a race to save CyberCity from a deadly virus. Helping him on his perilous mission is his partner, Sara Lee. The game is essentially an interactive movie done with 3D graphics. The player may i',
    c: 'https://cdn.mobygames.com/covers/3939883-cyberswine-windows-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/10150379-cyberswine-windows-unholy-pig-human-experiments.jpg',
      'https://cdn.mobygames.com/screenshots/10150358-cyberswine-windows-our-hero-cyberswine.jpg',
      'https://cdn.mobygames.com/screenshots/10150388-cyberswine-windows-cock-a-doodle-doo-motherfucker.jpg',
      'https://cdn.mobygames.com/screenshots/10150364-cyberswine-windows-pose-for-the-camera.jpg',
      'https://cdn.mobygames.com/screenshots/10150382-cyberswine-windows-the-pain-button-not-unlike-playing-this-game.jpg',
    ],
    g: [0, 91, 80, 3],
    p: [0],
  },
  {
    i: 1,
    n: 'The X-Files Game',
    l: 'https://www.mobygames.com/game/1/the-x-files-game/',
    d: '<p>As an extension of one of the most long-running television series of all time, <em>The X-Files</em>, play through the eyes of Special Agent Craig Willmore, a new FBI field investigator brought in to locate missing agents Fox Mulder and Dana Scully whose last location was the E',
    c: 'https://cdn.mobygames.com/covers/4062982-the-x-files-game-windows-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/11075554-the-x-files-game-windows-dockside-warehouse-under-surveillance.jpg',
      'https://cdn.mobygames.com/screenshots/11073355-the-x-files-game-windows-arriving-at-comity-inn.jpg',
      'https://cdn.mobygames.com/screenshots/11076738-the-x-files-game-windows-a-cigarette.jpg',
      'https://cdn.mobygames.com/screenshots/3874741-the-x-files-game-windows-agent-willmores-office-and-the-inventor.jpg',
      'https://cdn.mobygames.com/screenshots/10471109-the-x-files-game-playstation-catching-on-some-clues-wrong-answer.jpg',
    ],
    g: [0, 1, 2, 3, 4, 5],
    p: [0, 1, 2],
  },
  {
    i: 92,
    n: 'Altered Destiny',
    l: 'https://www.mobygames.com/game/92/altered-destiny/',
    d: '<p>One fine day P. J. Barrett, an ordinary human being from the planet Earth, goes to a repair shop to get his TV set fixed. When he comes back for it, he accidentally picks up the wrong one. No big deal? Quite on the contrary. When the unsuspecting Mr. Barrett returns home and t',
    c: 'https://cdn.mobygames.com/covers/3899950-altered-destiny-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/1694785-altered-destiny-dos-the-floating-village.png',
      'https://cdn.mobygames.com/screenshots/15806627-altered-destiny-amiga-help-screen.png',
      'https://cdn.mobygames.com/screenshots/1695597-altered-destiny-dos-ask-the-sage-a-question.png',
      'https://cdn.mobygames.com/screenshots/16048600-altered-destiny-amiga-copy-protection.png',
      'https://cdn.mobygames.com/screenshots/15806993-altered-destiny-amiga-intro-tv-repair-shop.png',
    ],
    g: [0, 39, 44, 45, 3],
    p: [3, 0, 4],
  },
  {
    i: 98,
    n: 'Rise of the Dragon',
    l: 'https://www.mobygames.com/game/98/rise-of-the-dragon/',
    d: "<p>The year is 2053, and Los Angeles has turned into a grim place ruled by crime and corruption. William 'Blade' Hunter is a private detective who once was a police officer. He is asked to investigate a horrible murder of the mayor's daughter, whose body was mutilated. As Hunter ",
    c: 'https://cdn.mobygames.com/covers/4014463-rise-of-the-dragon-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/16460458-rise-of-the-dragon-amiga-discussion-with-the-mayor.png',
      'https://cdn.mobygames.com/screenshots/2348780-rise-of-the-dragon-dos-id-do-as-he-says-if-i-were-you.png',
      'https://cdn.mobygames.com/screenshots/15756165-rise-of-the-dragon-sega-cd-one-of-the-arcade-segments-near-the-e.png',
      'https://cdn.mobygames.com/screenshots/11584691-rise-of-the-dragon-macintosh-the-em-way.png',
      'https://cdn.mobygames.com/screenshots/16460437-rise-of-the-dragon-amiga-downtown.png',
    ],
    g: [0, 1, 44, 80, 4],
    p: [3, 0, 4, 9, 2],
  },
  {
    i: 116,
    n: 'Gabriel Knight: Sins of the Fathers',
    l: 'https://www.mobygames.com/game/116/gabriel-knight-sins-of-the-fathers/',
    d: '<p>Gabriel Knight is a wise-cracking bookstore owner and would-be author. He is the last in a long line of Shadow Hunters, those fated to fight supernatural forces of evil. Tormented by terrifying nightmares, he must spend every waking moment scouring the side streets and back al',
    c: 'https://cdn.mobygames.com/covers/10943030-gabriel-knight-sins-of-the-fathers-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/1264759-gabriel-knight-sins-of-the-fathers-dos-bloody-ritual.png',
      'https://cdn.mobygames.com/screenshots/12166030-gabriel-knight-sins-of-the-fathers-dos-this-video-animation-show.png',
      'https://cdn.mobygames.com/screenshots/8787484-gabriel-knight-sins-of-the-fathers-dos-like-in-most-sierra-games.png',
      'https://cdn.mobygames.com/screenshots/8787481-gabriel-knight-sins-of-the-fathers-dos-bookstore-gabriels-home-b.png',
      'https://cdn.mobygames.com/screenshots/8786915-gabriel-knight-sins-of-the-fathers-dos-the-map-of-french-distric.png',
    ],
    g: [0, 36, 49, 44, 45, 20, 4, 79],
    p: [3, 0, 16, 2],
  },
  {
    i: 118,
    n: 'The Beast Within: A Gabriel Knight Mystery',
    l: 'https://www.mobygames.com/game/118/the-beast-within-a-gabriel-knight-mystery/',
    d: '<p><em>The Beast Within: A Gabriel Knight Mystery</em> is a direct sequel to <a href="https://www.mobygames.com/game/116/gabriel-knight-sins-of-the-fathers/">Gabriel Knight: Sins of the Fathers</a>, the first in the supernatural mystery adventure series telling the story of a boo',
    c: 'https://cdn.mobygames.com/covers/416469-the-beast-within-a-gabriel-knight-mystery-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/109403-the-beast-within-a-gabriel-knight-mystery-dos-yup-these-things-h.png',
      'https://cdn.mobygames.com/screenshots/95513-the-beast-within-a-gabriel-knight-mystery-windows-gerda-a-firey-.png',
      'https://cdn.mobygames.com/screenshots/107424-the-beast-within-a-gabriel-knight-mystery-dos-while-in-wolfs-sha.png',
      'https://cdn.mobygames.com/screenshots/8690773-the-beast-within-a-gabriel-knight-mystery-dos-certain-key-events.png',
      'https://cdn.mobygames.com/screenshots/12314189-the-beast-within-a-gabriel-knight-mystery-windows-it-was-a-close.jpg',
    ],
    g: [0, 39, 45, 20, 4, 79],
    p: [3, 0, 16, 2],
  },
  {
    i: 132,
    n: 'Call of Cthulhu: Shadow of the Comet',
    l: 'https://www.mobygames.com/game/132/call-of-cthulhu-shadow-of-the-comet/',
    d: "<p>In 1834, in the small New England fishing village of Illsmouth, the distinguished British scientist Lord Boleskine lost his mind. After studying ancient manuscripts of evil repute, he had travelled to this place to observe the passing of Halley's comet. What he observed that n",
    c: 'https://cdn.mobygames.com/covers/4022611-call-of-cthulhu-shadow-of-the-comet-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/15647947-call-of-cthulhu-shadow-of-the-comet-pc-98-its-easy-to-get-lost.png',
      'https://cdn.mobygames.com/screenshots/16099292-call-of-cthulhu-shadow-of-the-comet-pc-98-the-graphics-in-this-g.png',
      'https://cdn.mobygames.com/screenshots/16098386-call-of-cthulhu-shadow-of-the-comet-pc-98-do-you-feel-patriotic.png',
      'https://cdn.mobygames.com/screenshots/16098383-call-of-cthulhu-shadow-of-the-comet-pc-98-arriving-at-the-sleepy.png',
      'https://cdn.mobygames.com/screenshots/16098314-call-of-cthulhu-shadow-of-the-comet-pc-98-this-cu-scene-is-displ.png',
    ],
    g: [0, 36, 44, 45, 34, 79, 5],
    p: [35, 3, 0, 26],
  },
  {
    i: 135,
    n: "Roberta Williams' King's Quest VII: The Princeless Bride",
    l: 'https://www.mobygames.com/game/135/roberta-williams-kings-quest-vii-the-princeless-bride/',
    d: '<p>Queen Valanice of Daventry has always thought that getting married would be the best course of action for her daughter Rosella. However, the young princess seems to be more interested in adventure, recklessly following a mysterious magical creature into a whirlpool that eventu',
    c: 'https://cdn.mobygames.com/covers/9205765-roberta-williams-kings-quest-vii-the-princeless-bride-dos-front-.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/12247543-roberta-williams-kings-quest-vii-the-princeless-bride-dos-the-gr.png',
      'https://cdn.mobygames.com/screenshots/12246743-roberta-williams-kings-quest-vii-the-princeless-bride-dos-the-in.png',
      'https://cdn.mobygames.com/screenshots/16746370-roberta-williams-kings-quest-vii-the-princeless-bride-windows-a-.png',
      'https://cdn.mobygames.com/screenshots/1359898-roberta-williams-kings-quest-vii-the-princeless-bride-dos-no-kin.png',
      'https://cdn.mobygames.com/screenshots/16746361-roberta-williams-kings-quest-vii-the-princeless-bride-windows-tr.png',
    ],
    g: [0, 39, 44, 45, 20, 60],
    p: [3, 0, 16, 2],
  },
  {
    i: 136,
    n: "King's Quest: Mask of Eternity",
    l: 'https://www.mobygames.com/game/136/kings-quest-mask-of-eternity/',
    d: '<p>The Realm of Sun is a magical world situated above the Kingdom of Daventry. Powerful beings known as Archons dwell there, guarding the Mask of Eternity, which preserves balance in the world. But on an ominous day, Lucreto, the leader of the Archons, turns evil and shatters the',
    c: 'https://cdn.mobygames.com/covers/3979754-kings-quest-mask-of-eternity-windows-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/16813561-kings-quest-mask-of-eternity-windows-thought-perhaps-its-not-yet.png',
      'https://cdn.mobygames.com/screenshots/9113804-kings-quest-mask-of-eternity-windows-pick-up-and-eat-the-mushroo.jpg',
      'https://cdn.mobygames.com/screenshots/10276386-kings-quest-mask-of-eternity-windows-a-daventry-fountain.jpg',
      'https://cdn.mobygames.com/screenshots/583602-kings-quest-mask-of-eternity-windows-title-screen.jpg',
      'https://cdn.mobygames.com/screenshots/10270528-kings-quest-mask-of-eternity-windows-receiving-a-map-from-the-wi.jpg',
    ],
    g: [6, 0, 78, 1, 33, 45, 60],
    p: [0],
  },
  {
    i: 145,
    n: 'Space Quest 6: Roger Wilco in the Spinal Frontier',
    l: 'https://www.mobygames.com/game/145/space-quest-6-roger-wilco-in-the-spinal-frontier/',
    d: '<p>Roger Wilco, the brave interstellar janitor who has already saved the universe from many great dangers, is now in a very embarrassing position. His commanders show no respect for his courageous actions in the <a href="https://www.mobygames.com/game/144/space-quest-v-the-next-m',
    c: 'https://cdn.mobygames.com/covers/4028930-space-quest-6-roger-wilco-in-the-spinal-frontier-dos-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/9895156-space-quest-6-roger-wilco-in-the-spinal-frontier-dos-a-message-f.png',
      'https://cdn.mobygames.com/screenshots/1924395-space-quest-6-roger-wilco-in-the-spinal-frontier-windows-3x-hote.jpg',
      'https://cdn.mobygames.com/screenshots/9894403-space-quest-6-roger-wilco-in-the-spinal-frontier-dos-stellas-fun.png',
      'https://cdn.mobygames.com/screenshots/10408398-space-quest-6-roger-wilco-in-the-spinal-frontier-windows-3x-in-t.jpg',
      'https://cdn.mobygames.com/screenshots/12024110-space-quest-6-roger-wilco-in-the-spinal-frontier-windows-3x-inve.png',
    ],
    g: [0, 36, 44, 45, 20, 3, 55],
    p: [3, 0, 16, 2],
  },
  {
    i: 157,
    n: 'Cyberswine',
    l: 'https://www.mobygames.com/game/157/cyberswine/',
    d: '<p>The protagonist of <em>Cyberswine</em> is, as the title implies, a cybernetic pig on a race to save CyberCity from a deadly virus. Helping him on his perilous mission is his partner, Sara Lee. The game is essentially an interactive movie done with 3D graphics. The player may i',
    c: 'https://cdn.mobygames.com/covers/3939883-cyberswine-windows-front-cover.jpg',
    s: [
      'https://cdn.mobygames.com/screenshots/10150379-cyberswine-windows-unholy-pig-human-experiments.jpg',
      'https://cdn.mobygames.com/screenshots/10150358-cyberswine-windows-our-hero-cyberswine.jpg',
      'https://cdn.mobygames.com/screenshots/10150388-cyberswine-windows-cock-a-doodle-doo-motherfucker.jpg',
      'https://cdn.mobygames.com/screenshots/10150364-cyberswine-windows-pose-for-the-camera.jpg',
      'https://cdn.mobygames.com/screenshots/10150382-cyberswine-windows-the-pain-button-not-unlike-playing-this-game.jpg',
    ],
    g: [0, 91, 80, 3],
    p: [0],
  },
];
